version: "3.1"
services:
  postgres:
    image: "postgres:12.3"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    #   env_file: .env # Loads secrets from .env file and makes available to PSQL
  app:
    image: tylerauer/reddit:latest
    restart: always
    depends_on:
      - postgres
    volumes:
      - /app/node_modules # Saves from having to rebuild this folder over and over
    ports:
      # Makes the app accessible from port 80
      # SYNTAX: [external port:internal port]
      - "80:4000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      COOKIE_SESSION_SECRET: ${COOKIE_SESSION_SECRET}
    #   env_file: .env # Loads secrets from .env file and makes available to app.js
