version: "3.1"
services:
  postgres:
    image: "postgres:12.3"
    restart: always
    environment:
      env_file: .env # Loads secrets from .env file and makes available to PSQL
  app:
    image: tylerauer/reddit:alpha
    restart: always
    depends_on:
      - postgres
    volumes:
      - /app/node_modules # Saves from having to rebuild this folder over and over
    ports:
      # Makes the app accessible from port 80
      # SYNTAX: [external port:internal port]
      - "80:4000"
    environment:
      env_file: .env # Loads secrets from .env file and makes available to app.js
