version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  backend:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev # Just the name of the Dockerfile
      context: ./backend # Where to find the Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  frontend:
    stdin_open: true
    ports:
      - '3000:3000'
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules # don't need to copy over the node_module contents from local
      - ./frontend:/app # DO need to copy over everything in the client folder
