version: "3.1"
services:
  postgres:
    image: "postgres:12.3"
    restart: always
    env_file: .env # Loads secrets from .env file and makes available to PSQL
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
    ports:
      - "4000:4000"
    env_file: .env # Loads secrets from .env file and makes available to app.js
    restart: always
